# -*- coding: utf-8 -*-
"""여기어때크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1To60Afujd1l-hPv1EwyblfbQrglyxELN
"""

import requests
from bs4 import BeautifulSoup
import json
from tqdm.notebook import tqdm
import re



total_page =[]
url = 'https://www.goodchoice.kr/product/get_review_non'
headers = {
    'referer': 'https://www.goodchoice.kr/product/detail?ano=66650&adcno=2&sel_date=2022-07-20&sel_date2=2022-08-22',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
}

data = {
    'page': '0',
    'ano': '66650'
}
resp = requests.post(url, headers = headers, data=data)
comment = json.loads(resp.text)
total_page = int(comment['result']['total_page_cnt'])
total_page

#각 호텔의 고유 id를 가지고 오는 코드
hotel_id = []
all_hotel = []
for i in tqdm(range(2051,2057)):
  url = f'https://www.goodchoice.kr/product/search/2/{i}?sel_date=2022-08-27&sel_date2=2022-08-28'
  headers = {
      'referer': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
      'user-agent': 'https://www.goodchoice.kr/'
  }

  resp = requests.post(url, headers = headers)
  all_hotel.append(re.findall('ano=(.+?)&',resp.text))
for i in range(len(all_hotel)):
  for j in range(len(all_hotel[i])):
    hotel_id.append(all_hotel[i][j])

hotel_id

#각 호텔의 주소를 가지고 오는 코드
address = []
for i in tqdm(hotel_id):
  url = f'https://www.goodchoice.kr/product/detail?ano={i}&adcno=2&sel_date=2022-07-21&sel_date2=2022-07-22'
  resp = requests.get(url)
  a = re.findall('<p class="address">(.+?)</p>',resp.text)
  address.append(a[0])

address

all_comment = {
    '이름':[],
    '리뷰':[],
    '별점':[],
    '주소':[]
}
for link in tqdm(range(len(hotel_id))):
  url = 'https://www.goodchoice.kr/product/get_review_non'
  headers = {
      'referer': f'https://www.goodchoice.kr/product/detail?ano={hotel_id[link]}&adcno=2&sel_date=2022-07-20&sel_date2=2022-07-21',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
  }

  for page in range(total_page+1):
    data = {
        'page': page,
        'ano': hotel_id[link]
    }
    resp = requests.post(url, headers = headers, data=data)
    comment = json.loads(resp.text)
    hotel_review = comment['result']['items']
    for review in range(len(hotel_review)):
      review_score = hotel_review[review]['epilrate']
      if(review_score>=5):
        all_comment['리뷰'].append(hotel_review[review]['aepcont'])
        all_comment['별점'].append(hotel_review[review]['epilrate'])
        all_comment['이름'].append(hotel_review[review]['aname'])
        all_comment['주소'].append(address[link])
all_comment

import pandas as pd

df_hotel_comment = pd.DataFrame(all_comment)

df_hotel_comment

df_hotel_comment.to_csv('hotel_comment.csv', index=False, encoding="utf-8-sig")

